# Generated by Django 4.1.7 on 2023-10-14 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=150)),
                ('event_id', models.CharField(max_length=30)),
                ('event_time', models.CharField(max_length=50)),
                ('event_location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='guest',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('userid', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('email_id', models.CharField(max_length=120)),
                ('pswd', models.CharField(max_length=30)),
                ('phone_num', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='userEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.guest')),
            ],
        ),
    ]
