# Generated by Django 4.2.6 on 2023-10-15 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userevent_event_id_userevent_event_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userevent',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='userevent',
            name='event_name',
        ),
    ]
