# Generated by Django 4.2.6 on 2023-10-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_userevent_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='event_id',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='userevent',
            name='event_name',
            field=models.CharField(default='guest talk', max_length=255),
        ),
    ]
