# Generated by Django 4.2.6 on 2023-10-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userevent_event_id_userevent_event_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userevent',
            name='event_name',
        ),
        migrations.AlterField(
            model_name='userevent',
            name='event_id',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
