# Generated by Django 4.2.6 on 2023-10-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_userevent_event_name_alter_userevent_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userevent',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
