# Generated by Django 4.2.6 on 2023-10-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_userevent_attended_userevent_registered'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedPrime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
