# Generated by Django 4.2.6 on 2023-10-15 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_generatedprime_prime_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedprime',
            name='prime_id',
        ),
    ]
